Traceback (most recent call last):
  File "C:\Users\mirjam\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\mirjam\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tree = ET.parse('ddd_010097934_mpeg21_a0001_ocr.xml')
root_article = tree.getroot()
print(ET.tostring(root_article, encoding='utf8').decode('utf8'))
------------------

Traceback [1;36m(most recent call last)[0m:

  File [0;32m~\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369[0m in [0;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input [0;32mIn [9][0m in [0;35m<cell line: 1>[0m
    tree = ET.parse('ddd_010097934_mpeg21_a0001_ocr.xml')

  File [0;32m~\anaconda3\lib\xml\etree\ElementTree.py:1229[0m in [0;35mparse[0m
    tree.parse(source, parser)

[1;36m  File [1;32m~\anaconda3\lib\xml\etree\ElementTree.py:580[1;36m in [1;35mparse[1;36m[0m
[1;33m    self._root = parser._parse_whole(source)[0m

[1;36m  File [1;32m<string>[1;36m[0m
[1;31mParseError[0m[1;31m:[0m no element found: line 1, column 0

ParseError: no element found: line 1, column 0 (<string>)

